// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
	PassHash []byte      `json:"pass_hash"`
	PassSalt []byte      `json:"pass_salt"`
	Role     string      `json:"role"`
}
