// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID               int32              `json:"id"`
	ProductID        int32              `json:"product_id"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	AvailabilityType string             `json:"availability_type"`
	Days             int32              `json:"days"`
	Hours            int32              `json:"hours"`
	Price            int32              `json:"price"`
	MaxParticipants  int32              `json:"max_participants"`
	Precedance       int32              `json:"precedance"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Timezone  string      `json:"timezone"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
	PassHash []byte      `json:"pass_hash"`
	PassSalt []byte      `json:"pass_salt"`
	Role     string      `json:"role"`
}
