// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    timezone,
    created_by
)
VALUES (
    $1, $2, $3
)
RETURNING id, name, timezone
`

type CreateProductParams struct {
	Name      string      `json:"name"`
	Timezone  string      `json:"timezone"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type CreateProductRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Timezone, arg.CreatedBy)
	var i CreateProductRow
	err := row.Scan(&i.ID, &i.Name, &i.Timezone)
	return i, err
}
